### ISSUE TITLE
Inadyn docker can't create PID file

### ISSUE THREAD

**Issue by robfuscator** [troglobit/inadyn#243]
I'm using Inadyn in a docker-compose setup and I'm getting this error every time I bring the service up:

`inadyn_1   | inadyn[1]: Failed creating pidfile: No such file or directory`

It seems to work anyway. If I force the IP update, I get the correct log entry. I can't tell for sure because my IP doesn't change very often.

My `docker-compose.yml` looks like this (config is copied during build process):

```yaml
version: '3.7'

services:
    inadyn:
        build: ./containers/inadyn
        restart: always
```
