### ISSUE TITLE
When running inadyn as unprivileged user, it will complain about not able to chown the cache-dir. 

### ISSUE THREAD

**Issue by leonyu** [troglobit/inadyn#309]
When running inadyn as unprivileged user, it will complain about not able to `chown` the cache-dir. 

> Cannot change owner of cache directory /tmp/.inadyn/ to 0:0, skipping: Operation not permitted

Can be produced with the following docker/docker-compose setup: 

```yaml
services:
  inadyn:
    image: troglobit/inadyn:latest
    entrypoint: inadyn --foreground --cache-dir=/tmp/.inadyn/ --no-pidfile
    volumes:
      - ./inadyn.conf:/etc/inadyn.conf
    user: nobody:nogroup
```
